import type { ConceptTypeId, Question } from '@/types';

export const QUESTIONS_BY_TYPE: Record<ConceptTypeId, Question[]> = {
  function: [
    {
      id: 'product',
      label: '제품/서비스는 무엇인가요?',
      placeholder: '예: 천연 성분 탈취 스프레이',
      type: 'text',
      required: true,
    },
    {
      id: 'category',
      label: '어떤 카테고리(시장)에 속하나요?',
      placeholder: '예: 생활용품 > 탈취제 시장',
      type: 'text',
      required: true,
    },
    {
      id: 'coreTech',
      label: '핵심 성분, 기술, 또는 작동 원리는 무엇인가요?',
      placeholder: '예: 유산균 기반 미생물이 냄새 분자를 분해하는 방식',
      type: 'textarea',
      required: true,
      maxLength: 300,
    },
    {
      id: 'differentiation',
      label: '기존 경쟁 제품 대비 어떤 점이 다른가요?',
      placeholder: '예: 기존 탈취제는 향으로 덮지만, 우리 제품은 냄새 원인균 자체를 먹어서 제거',
      type: 'textarea',
      required: true,
      maxLength: 300,
    },
    {
      id: 'painPoint',
      label: '고객이 현재 느끼는 가장 큰 불편함은?',
      placeholder: '예: 탈취제를 뿌려도 시간이 지나면 다시 냄새가 남',
      type: 'textarea',
      required: true,
      maxLength: 300,
    },
  ],

  seller: [
    {
      id: 'product',
      label: '어떤 제품/서비스를 판매하고 있나요?',
      placeholder: '예: 미생물 기반 탈취 스프레이',
      type: 'text',
      required: true,
    },
    {
      id: 'background',
      label: '당신의 배경과 이력은 어떻게 되나요?',
      placeholder: '예: 미생물학 전공, 연구소 10년 근무 후 창업',
      type: 'textarea',
      required: true,
      maxLength: 300,
    },
    {
      id: 'motivation',
      label: '이 사업을 시작한 계기는 무엇인가요?',
      placeholder: '예: 아이가 아토피로 고생해서 직접 안전한 제품을 만들기로 결심',
      type: 'textarea',
      required: true,
      maxLength: 300,
    },
    {
      id: 'expertise',
      label: '당신만의 전문성이나 집착 포인트는?',
      placeholder: '예: 성분 하나하나 직접 실험하고 기록하는 습관, 300번 이상 배합 테스트',
      type: 'textarea',
      required: true,
      maxLength: 300,
    },
    {
      id: 'desiredImage',
      label: '고객에게 어떤 이미지로 다가가고 싶나요?',
      placeholder: '예: 친근한 동네 형 같으면서도 전문가인 느낌',
      type: 'textarea',
      required: true,
      maxLength: 300,
    },
  ],

  'customer-identity': [
    {
      id: 'product',
      label: '제품/서비스는 무엇인가요?',
      placeholder: '예: 남성용 마그네슘 올인원 바디워시',
      type: 'text',
      required: true,
    },
    {
      id: 'targetCustomer',
      label: '타겟 고객의 연령/성별/직업은?',
      placeholder: '예: 30대 남성, 직장인, 운동을 즐기는 사람',
      type: 'textarea',
      required: true,
      maxLength: 300,
    },
    {
      id: 'desiredIdentity',
      label: '이 제품을 사는 고객은 어떤 사람이 되고 싶어하나요?',
      placeholder: '예: 자기관리를 철저히 하는 멋진 남자',
      type: 'textarea',
      required: true,
      maxLength: 300,
    },
    {
      id: 'lifestyle',
      label: '타겟 고객의 라이프스타일 키워드는?',
      placeholder: '예: 새벽 운동, 단백질 쉐이크, 깔끔한 데스크 셋업',
      type: 'textarea',
      required: true,
      maxLength: 300,
    },
    {
      id: 'belongingGroup',
      label: '고객이 소속되고 싶은 그룹이나 정체성은?',
      placeholder: '예: "남들과 다르게 관리하는 상위 5% 남자들"',
      type: 'textarea',
      required: true,
      maxLength: 300,
    },
  ],

  situation: [
    {
      id: 'product',
      label: '제품/서비스는 무엇인가요?',
      placeholder: '예: 레몬즙 음료',
      type: 'text',
      required: true,
    },
    {
      id: 'currentUsage',
      label: '현재 주요 사용 상황은 어떻게 되나요?',
      placeholder: '예: 요리할 때 레몬즙으로 사용, 또는 물에 타서 음용',
      type: 'textarea',
      required: true,
      maxLength: 300,
    },
    {
      id: 'criticalMoment',
      label: '고객이 이 제품을 가장 필요로 하는 순간은?',
      placeholder: '예: 아침 공복에 건강 루틴으로 마시고 싶을 때',
      type: 'textarea',
      required: true,
      maxLength: 300,
    },
    {
      id: 'dailyPain',
      label: '일상에서 반복되는 불편한 상황이 있다면?',
      placeholder: '예: 매일 아침 뭘 먹어야 건강해지는지 고민, 루틴이 없는 불안함',
      type: 'textarea',
      required: true,
      maxLength: 300,
    },
    {
      id: 'timingContext',
      label: '계절, 시간대, 이벤트 중 연결 가능한 것은?',
      placeholder: '예: 월요일 아침, 운동 후, 다이어트 시즌, 새해 결심 시기',
      type: 'textarea',
      required: true,
      maxLength: 300,
    },
  ],

  'business-model': [
    {
      id: 'product',
      label: '제품/서비스는 무엇인가요?',
      placeholder: '예: 파라핀 왁스 관절 관리 기기',
      type: 'text',
      required: true,
    },
    {
      id: 'currentSalesMethod',
      label: '현재 판매 방식과 가격대는?',
      placeholder: '예: 스마트스토어에서 단품 판매, 49,000원',
      type: 'textarea',
      required: true,
      maxLength: 300,
    },
    {
      id: 'repurchaseCycle',
      label: '재구매 주기는 어떻게 되나요?',
      placeholder: '예: 리필용 왁스는 2개월마다, 기기 자체는 1~2년',
      type: 'textarea',
      required: true,
      maxLength: 300,
    },
    {
      id: 'customerTouchpoint',
      label: '고객과의 접점은 어디인가요? (온라인/오프라인)',
      placeholder: '예: 네이버 스마트스토어, 인스타그램 DM, 카카오톡 채널',
      type: 'textarea',
      required: true,
      maxLength: 300,
    },
    {
      id: 'salesChallenge',
      label: '현재 가장 큰 판매 구조 고민은?',
      placeholder: '예: 첫 구매 전환율이 낮음, 체험 없이 고가 제품을 사게 하기 어려움',
      type: 'textarea',
      required: true,
      maxLength: 300,
    },
  ],
};
